---
- hosts: evolvemaster
  become: yes
  
  vars_files:
    - vars.yml

  tasks:
    - name: Get the MAC address
      debug: msg="{{ hostvars[inventory_hostname].ansible_eth0.macaddress }}"
    - name: Set the current MAC address for eth0.
      set_fact:
        evolvemaster_mac_address: "{{ hostvars[inventory_hostname].ansible_eth0.macaddress }}"
    - name: Set variables based on eth0 MAC address.
      set_fact:
        evolvemaster_hostname: "{{ mac_address_mapping[evolvemaster_mac_address].name }}"
        evolvemaster_ip_address: "{{ mac_address_mapping[evolvemaster_mac_address].ip }}"
    - name: Set up networking-related files.
      template:
        src: "templates/{{ item.template }}"
        dest: "{{ item.dest }}"
        mode: 0644
      with_items:
        - { template: hostname.j2, dest: /etc/hostname }
        - { template: hosts.j2, dest: /etc/hosts }
        - { template: dhcpcd.conf.j2, dest: /etc/dhcpcd.conf }
      notify:
        - update hostname
        - delete dhcp leases

  handlers:
    - name: update hostname
      command: "hostname {{ evolvemaster_hostname }}"

    - name: delete dhcp leases
      file:
        path: /var/lib/dhcp/dhclient.leases
        state: absent
      with_items:
        - /var/lib/dhcp/dhclient.leases
        - /var/lib/dhcpcd5/dhcpcd-eth0.lease